spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3315/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      keepalive-time: 30_000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        ddl-auto: update
        show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    converters:
      preferred-json-mapper: gson
  mail:
    host: smtp.gmail.com
    username: hideonbush8405
    password: okcu xvrk eblg accw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# server
server:
  port: 8080
  servlet:
    context-path: /api
# eiml khhq agwv gucp


