spring:
  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12660173?useSSL=false&serverTimezone=UTC
    username: sql12660173
    password: GkjQACv2pf
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      keepalive-time: 30_000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        ddl-auto: update
        show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    converters:
      preferred-json-mapper: gson

# server
server:
  port: 8080
  servlet:
    context-path: /api
